"""
Generate src/kernel/kernel_exports.h from tools/xboxkrnl.exe.def (nxdk).
"""
import re

rows = []
for line in open("tools/xboxkrnl.exe.def"):
    m = re.match(r"\s*(@?)(\w+)(?:@(\d+))?\s+@\s*(\d+)\s+NONAME(\s+DATA)?", line)
    if not m:
        continue
    fastcall, name, n, ordinal, data = m.groups()
    n = int(n) if n else 0
    # stack bytes the callee pops: stdcall = N, fastcall = N minus ecx/edx,
    # cdecl (no decoration, e.g. DbgPrint) = 0
    stack = max(0, n - 8) if fastcall else n
    rows.append((int(ordinal), name, stack, 1 if data else 0))

with open("src/kernel/kernel_exports.h", "w") as f:
    f.write("/* Generated by tools/gen_kernel_exports.py from tools/xboxkrnl.exe.def\n"
            " * (nxdk). Do not edit. */\n#pragma once\n\n")
    f.write("typedef struct { unsigned short ordinal; const char *name; "
            "unsigned char stack_bytes; unsigned char is_data; } xbox_kernel_export;\n\n")
    f.write("static const xbox_kernel_export g_xbox_kernel_exports[] = {\n")
    for o, name, st, d in sorted(rows):
        f.write(f'    {{ {o:3d}, "{name}", {st}, {d} }},\n')
    f.write("};\n#define XBOX_KERNEL_EXPORT_COUNT "
            "(sizeof(g_xbox_kernel_exports) / sizeof(g_xbox_kernel_exports[0]))\n")
print(len(rows), "exports")
